version: '3.9'

services:
  app-crons-service:
    container_name: app-crons-service
    build: .
    command: npm run prod
    env_file: .env
    restart: always
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
